axis_linear: 1
scale_linear: 0.7
scale_linear_turbo: 1.2

axis_angular: 0
scale_angular: 0.7
scale_angular_turbo: 1.2

enable_button: 6  # L2 shoulder button
enable_turbo_button: 7  # R2 shoulder button