#Diff_Drive:
  diff_drive_controller:
    type: "diff_drive_controller/DiffDriveController"
    publish_rate: 50

    left_wheel: ['left_front_wheel_joint','left_back_wheel_joint']
    right_wheel: ['right_front_wheel_joint','right_back_wheel_joint']

    #wheel_separation: 0.4
    #wheel_radius: 0.095
    # Odometry covariances for the encoder output of the robot. These values should
    # be tuned to your robot's sample odometry data, but these values are a good place
    # to start
    pose_covariance_diagonal: [0.000, 0.000, 000000.0, 000000.0, 000000.0, 0.00]
    twist_covariance_diagonal: [0.00, 0.00, 000000.0, 000000.0, 000000.0, 0.00]

    # Top level frame (link) of the robot description
    base_frame_id: base_footprint
    enable_odom_tf: true

    # Velocity and acceleration limits for the robot
    linear:
      x:
        has_velocity_limits    : false
        max_velocity           : 1  # m/s
        has_acceleration_limits: false
        max_acceleration       : 3   # m/s^2
    angular:
      z:
        has_velocity_limits    : false
        max_velocity           : 1   # rad/s
        has_acceleration_limits: false
        max_acceleration       : 3   # rad/s^2

# Read complete documentation here : http://wiki.ros.org/diff_drive_controller